### ISSUE TITLE
云开发者中心无法打开

### ISSUE THREAD

**Issue by jianghehe** [yonyou-iuap/iuap_pap_react#2]
http://iuap.yonyou.com/product/devplatform.html

**Comment by kvkens** [comment]
https://developer.yonyoucloud.com/

**Comment by jianghehe** [comment]
为什么关掉我的问题？




------------------ 原始邮件 ------------------
发件人: "YueMing"<notifications@github.com>; 
发送时间: 2019年5月5日(星期天) 中午12:29
收件人: "yonyou-iuap/iuap_pap_react"<iuap_pap_react@noreply.github.com>; 
抄送: "踌躇たかほ向前"<1397183731@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [yonyou-iuap/iuap_pap_react] 云开发者中心无法打开 (#2)




Closed #2.

**Comment by jianghehe** [comment]
请问一下为什么你们官网很多跳转的链接都不对呢？




------------------ 原始邮件 ------------------
发件人: "YueMing"<notifications@github.com>; 
发送时间: 2019年5月5日(星期天) 中午12:29
收件人: "yonyou-iuap/iuap_pap_react"<iuap_pap_react@noreply.github.com>; 
抄送: "踌躇たかほ向前"<1397183731@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [yonyou-iuap/iuap_pap_react] 云开发者中心无法打开 (#2)




https://developer.yonyoucloud.com/
